/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./src/assets/glbs/rocket.glb -t -o ./src/pages/contact/components/model/Rocket.tsx 
*/

import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";

type GLTFResult = GLTF & {
    nodes: {
        Cylinder: THREE.Mesh;
        Cylinder_1: THREE.Mesh;
        Cube: THREE.Mesh;
        Mball010: THREE.Mesh;
        Cube_1: THREE.Mesh;
        Cube_2: THREE.Mesh;
        Label: THREE.Mesh;
        Cube001: THREE.Mesh;
        Cube001_1: THREE.Mesh;
        Whatever: THREE.Mesh;
        Rocket_Window: THREE.Mesh;
        Sphere: THREE.Mesh;
    };
    materials: {
        ["Material.002"]: THREE.MeshStandardMaterial;
        ["Material.004"]: THREE.MeshStandardMaterial;
        ["Material.003"]: THREE.MeshStandardMaterial;
        rocket: THREE.MeshStandardMaterial;
        ["Rocket Top and motor"]: THREE.MeshStandardMaterial;
        ["Label Color"]: THREE.MeshStandardMaterial;
        ["Mini rocket "]: THREE.MeshStandardMaterial;
        Material: THREE.MeshStandardMaterial;
        ["Window Outer"]: THREE.MeshStandardMaterial;
    };
    animations: GLTFAction[];
};

type ActionName = "RanpaAction.001";
interface GLTFAction extends THREE.AnimationClip {
    name: ActionName;
}

export default function RocketModel(props: JSX.IntrinsicElements["group"]) {
    const recketRef = useRef<THREE.Group>(null);
    const { nodes, materials } = useGLTF("models/rocket.glb") as GLTFResult;

    useFrame(() => {});

    return (
        <group {...props} dispose={null}>
            <group ref={recketRef} name="Scene">
                <group
                    name="Ranpa"
                    position={[0.201, -4.923, 0]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={[-1.705, -0.055, -1.705]}
                >
                    <mesh
                        name="Cylinder"
                        geometry={nodes.Cylinder.geometry}
                        material={materials["Material.002"]}
                    />
                    <mesh
                        name="Cylinder_1"
                        geometry={nodes.Cylinder_1.geometry}
                        material={materials["Material.004"]}
                    />
                    <mesh
                        name="Cube"
                        geometry={nodes.Cube.geometry}
                        material={materials["Material.003"]}
                        position={[-0.035, -26.159, 0]}
                        rotation={[-Math.PI, 0, -Math.PI]}
                        scale={[-0.176, -22.361, -0.176]}
                    />
                    <mesh
                        name="Mball010"
                        geometry={nodes.Mball010.geometry}
                        material={materials["Material.003"]}
                        position={[-0.035, -5.974, 0]}
                        rotation={[-Math.PI, 0, -Math.PI]}
                        scale={[-0.176, -5.415, -0.176]}
                    />
                    <group
                        name="Rocket"
                        position={[-0.035, -65.354, 0]}
                        rotation={[-Math.PI, 0, -Math.PI]}
                        scale={[-0.176, -16.246, -0.176]}
                    >
                        <mesh
                            name="Cube_1"
                            geometry={nodes.Cube_1.geometry}
                            material={materials.rocket}
                        />
                        <mesh
                            name="Cube_2"
                            geometry={nodes.Cube_2.geometry}
                            material={materials["Rocket Top and motor"]}
                        />
                        <mesh
                            name="Label"
                            geometry={nodes.Label.geometry}
                            material={materials["Label Color"]}
                            position={[0.028, -0.126, 1.091]}
                            rotation={[1.645, -0.023, -0.001]}
                            scale={[0.299, 0.299, 0.101]}
                        />
                        <group
                            name="Mini_Rocket"
                            position={[-1.48, -0.876, -0.068]}
                            scale={[0.326, 0.333, 0.396]}
                        >
                            <mesh
                                name="Cube001"
                                geometry={nodes.Cube001.geometry}
                                material={materials["Mini rocket "]}
                            />
                            <mesh
                                name="Cube001_1"
                                geometry={nodes.Cube001_1.geometry}
                                material={materials.Material}
                            />
                            <mesh
                                name="Whatever"
                                geometry={nodes.Whatever.geometry}
                                material={materials["Mini rocket "]}
                                position={[1.296, -0.046, 0.189]}
                                scale={[-0.765, -0.141, -0.155]}
                            />
                        </group>
                        <mesh
                            name="Rocket_Window"
                            geometry={nodes.Rocket_Window.geometry}
                            material={materials["Window Outer"]}
                            position={[0, 0.24, 0.958]}
                            rotation={[-1.726, -0.104, 0.046]}
                            scale={[0.389, 0.388, 0.136]}
                        >
                            <mesh
                                name="Sphere"
                                geometry={nodes.Sphere.geometry}
                                material={materials.Material}
                                position={[-0.011, 0.059, 0.023]}
                                rotation={[-1.804, -0.076, 0.204]}
                                scale={[0.824, 0.824, 0.547]}
                            />
                        </mesh>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("models/rocket.glb");
